version: '3'

services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./api:/api
  #   ports:
  #     - '81:3000'
  #   restart: always
  #   networks:
  #     - langage-networks
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - '8080:3000'
    restart: always
    networks:
      - langage-networks

networks:
  langage-networks:
    driver: bridge
